# Generated by Django 6.0.2 on 2026-03-01 22:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('ean', models.CharField(blank=True, default=None, max_length=13, null=True, unique=True)),
                ('manufacturer', models.CharField(max_length=128)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_unit', models.CharField(choices=[('g', 'Gram'), ('ml', 'Milliliter')], max_length=8)),
                ('energy', models.FloatField()),
                ('fat', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('sugars', models.FloatField()),
                ('fiber', models.FloatField()),
                ('protein', models.FloatField()),
                ('salt', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
