# Generated by Django 6.0.2 on 2026-02-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='producer',
            new_name='manufacturer',
        ),
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
