# Generated by Django 6.0.2 on 2026-03-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_unit',
            new_name='unit',
        ),
    ]
