# Generated by Django 6.0.2 on 2026-03-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit',
            new_name='quantity_unit',
        ),
    ]
