# Generated by Django 6.0.2 on 2026-03-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_unit_product_quantity_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrient_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('ml', 'Milliliter')], default='g', max_length=8),
            preserve_default=False,
        ),
    ]
