# Generated by Django 6.0.2 on 2026-03-10 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_nutrient_unit'),
        ('recipes', '0002_recipe_created_at_recipe_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='recipes.recipe'),
        ),
    ]
