# Generated by Django 6.0.2 on 2026-03-12 16:04

from django.db import migrations, models
from products.services import get_density_by_product_name


def populate_density(apps, schema_editor):
    Product = apps.get_model("products", "Product")

    for product in Product.objects.filter(nutrient_unit="ml"):
        product.density = get_density_by_product_name(product.name)
        product.save(update_fields=["density"])

        print(f"Product: {product.name}, density: {product.density}")

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_synced_at',
        ),
        migrations.AddField(
            model_name='product',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.RunPython(populate_density, migrations.RunPython.noop),
    ]
