# Generated by Django 6.0.2 on 2026-03-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_last_synced_at_product_density_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recipe',
        ),
    ]
