# Generated by Django 6.0.2 on 2026-03-17 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_issued_by'),
        ('recipes', '0003_ingredient_subrecipe_alter_ingredient_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='energy',
        ),
        migrations.AddField(
            model_name='product',
            name='energy_kcal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
