# Generated by Django 6.0.2 on 2026-03-17 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_manufacturer'),
        ('recipes', '0004_remove_ingredient_ingredient_product_or_subrecipe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('ean__isnull', True), ('recipe__isnull', True), _connector='OR'), name='product_ean_or_recipe_exclusive'),
        ),
    ]
