# Generated by Django 6.0.2 on 2026-03-12 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_recipe'),
        ('recipes', '0002_recipe_created_at_recipe_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='subrecipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='products.product'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('subrecipe__isnull', True)), models.Q(('product__isnull', True), ('subrecipe__isnull', False)), _connector='OR'), name='ingredient_product_or_subrecipe'),
        ),
    ]
