# Generated by Django 6.0.2 on 2026-03-17 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_manufacturer'),
        ('recipes', '0003_ingredient_subrecipe_alter_ingredient_product_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='ingredient_product_or_subrecipe',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='products.product'),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='subrecipe',
        ),
    ]
